version: "3"
services:
  db:
    image: postgres
    container_name: cleaning_robot_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cleaning_robot_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  web:
    image: node:12.13.0
    container_name: cleaning_robot_web
    command: npm start
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: cleaning_robot_db_dev
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      PORT: 5000
      HOST: 0.0.0.0
    build: .
    volumes:
      - ./:/src
    restart: always
